/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Graphics;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author DaniTini
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        // Ajustar la posición de los botones al tamaño de la ventana
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                ajustarPosiciones();
            }
        });
    }

    private void ajustarPosiciones() {
        int frameWidth = getWidth();
        int frameHeight = getHeight();

        // Ajuste para que los botones queden más centrados en los círculos amarillos
        int xReina = (int) (frameWidth * 0.37); // Ajustar para colocar debajo del ícono de la reina
        int xCaballo = (int) (frameWidth * 0.55); // Ajustar para colocar debajo del ícono del caballo
        int yPos = (int) (frameHeight * 0.70); // Ajustar para la posición vertical correcta

        btnReinas.setLocation(xReina, yPos);
        btnCaballo.setLocation(xCaballo, yPos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Iconos/Ajedrez.png"));
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(icon.getImage(),0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        btnCaballo = new javax.swing.JButton();
        btnReinas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCaballo.setForeground(new java.awt.Color(255, 255, 255));
        btnCaballo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/play32.png"))); // NOI18N
        btnCaballo.setText("Caballo");
        btnCaballo.setContentAreaFilled(false);
        btnCaballo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaballo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/play32.png"))); // NOI18N
        btnCaballo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/play64.png"))); // NOI18N
        btnCaballo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCaballo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCaballo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaballoActionPerformed(evt);
            }
        });

        btnReinas.setForeground(new java.awt.Color(255, 255, 255));
        btnReinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/play32.png"))); // NOI18N
        btnReinas.setText("Reinas");
        btnReinas.setContentAreaFilled(false);
        btnReinas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReinas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/play32.png"))); // NOI18N
        btnReinas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/play64.png"))); // NOI18N
        btnReinas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReinas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinasActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(btnCaballo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnReinas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(btnReinas)
                .addGap(69, 69, 69)
                .addComponent(btnCaballo)
                .addGap(326, 326, 326))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaballo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReinas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaballoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaballoActionPerformed
        ViewHorse view = new ViewHorse(null, false);
        view.setVisible(true);
        view.ejecutarRecorrido();
    }//GEN-LAST:event_btnCaballoActionPerformed

    private void btnReinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinasActionPerformed
        ViewReina view = new ViewReina(null, false);
        view.setVisible(true);
    }//GEN-LAST:event_btnReinasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu(null, true).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaballo;
    private javax.swing.JButton btnReinas;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables

    public class ImagenFondo extends JPanel {

        @Override
        public void paint(Graphics g) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/Iconos/Ajedrez.png"));
            g.drawImage(icon.getImage(), 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
