/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Juego.CaballoTablero;
import Piezas.Caballo;
import java.awt.BorderLayout;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author dashs
 */
public class ViewHorse extends javax.swing.JDialog {

    int N = 8;

    int[][] tablero = new int[N][N];
    Caballo caballo = new Caballo(tablero);
    CaballoTablero panelTablero = new CaballoTablero(tablero);

    /**
     * Creates new form ViewHorse
     *
     * @param parent
     * @param modal
     */
    public ViewHorse(java.awt.Frame parent, boolean modal) {
        setLayout(new BorderLayout());

        // Crear el panel que contendrá el tablero
        add(panelTablero, BorderLayout.CENTER);

        // Ajustar el tamaño
        setSize(600, 600);  // O ajusta el tamaño que necesites
        pack();
    }

    public void ejecutarRecorrido() {
        // Posición inicial del caballo
        int x = 0;
        int y = 0;

        // Configurar el punto inicial y ejecutar el recorrido
        JOptionPane.showMessageDialog(this, "Has iniciado en la posición [0,0]", "Recorrido del Caballo", JOptionPane.INFORMATION_MESSAGE);
        caballo.setIniticial(x, y);

        // Ejecutar el recorrido y actualizar el tablero
        if (caballo.recorridoCaballo(x, y, 1)) {
            panelTablero.actualizarTablero(caballo.getTablero());
            int contadorIntentos = caballo.getContadorIntentos();  // Obtener el número de intentos
            JOptionPane.showMessageDialog(this, "Recorrido completado en " + contadorIntentos + " intentos.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró una solución.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("¡Recorrido del Caballo!");
        setLocation(new java.awt.Point(222, 666));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHorse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHorse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHorse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHorse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewHorse dialog = new ViewHorse(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
